### ISSUE TITLE
如果xunsearch服务器与php代码不在同一个服务器，数据无法搜索到？

### ISSUE THREAD

**Issue by jihuago** [ShaoZeMing/xunsearch-laravel#1]
你好， 如果xunsearch服务器与php代码不在同一个服务器。

在搜索的时候，返回如下：
`array(8) {
  ["doc"] => array(0) {
  }
  ["hot"] => array(0) {
  }
  ["count"] => int(0)
  ["total"] => int(8)
  ["corrected"] => array(0) {
  }
  ["related"] => array(0) {
  }
  ["search_cost"] => float(0.0015010833740234)
  ["total_cost"] => float(0.0085008144378662)
}`

看到total是8,我刚好也是添加了8条数据，但是就是无法搜索出来数据

**Comment by ShaoZeMing** [comment]
很抱歉，最近很慢忙没有来打理这个，如果不在同一个服务器下，你将配置的链接地址IP改成你的讯搜地址就好。至于你说的搜索不到数据，我也不太清楚具体为什么，你方便把你代码拿出来我给你看一下吗？
