### ISSUE TITLE
  当数据没到达自定义数量的时候 它又重新把第一条数据开始填充？

### ISSUE THREAD

**Issue by meikoul** [ShaoZeMing/xunsearch-laravel#2]
![image](https://user-images.githubusercontent.com/21165904/33161526-13f255e0-d05f-11e7-9bed-192212a7bb65.png)
比如这只有一条数据 但是他循环显示了十次

**Comment by ShaoZeMing** [comment]
抱歉，回复晚了，并不是你想的那样，你应该是插入讯搜服务器多条相同的数据造成的原因
