### ISSUE TITLE
只有添加索引方法，没有更新索引方法吗？

### ISSUE THREAD

**Issue by hunteryun** [ShaoZeMing/xunsearch-laravel#3]

**Comment by ShaoZeMing** [comment]
抱歉，之前只是临时使用，没有更新，我暂时加入一个方法，composer 如果是国内镜像更新会延迟，这个包之前的，代码写的很烂，空了我重构封装一个版本

   
更新索引

            $data=[
            'pid'=>1,
            'subject'=>'关于 xunsearch 的 DEMO 项目测试,项目测试不怎么有意思！',
            'chrono'=>'1314336158'
            ];
            $xs = new \shaozeming\xunsearch\Search('demo');
      		$xs->updateIndexOne($data);   //更新索引


你也可以基于本包调用官方原生方法 ；
         
            $xs = new \shaozeming\xunsearch\Search('demo');
            $xs->getIndex()->update(new \XSDocument($data));

参考http://www.xunsearch.com/doc/php/guide/index.update

**Comment by hunteryun** [comment]
亲，别走，既然来都来了，把清空和删除一起加上嘛

**Comment by hunteryun** [comment]
呃，看到了，原来还可以调用原生方法，谢谢

**Comment by ShaoZeMing** [comment]
Ok，由于有朋友用了这个包，我不能轻易改动，最近公司任务太重，空了再来重构一下，规范一点。
